name : Node.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version}}
    - run: npm i
    - run: npm run build --if-present
    - run: npm run
#     - name: SSH Remote Commands
#       uses: appleboy/ssh-action@v0.1.8
#       with:
#         key: ${{secrets.MONGO_URL}}
#         port: ${{secrets.PORT}}
